const familyData = [
  {
    id: 0,
    name: "ラム",
    pids: [87],
    gender: "male",
    born: "1988/4/28-2012/3/30",
    locate: "東山動植物園",
  },
  {
    id: 1,
    name: "のぞみ",
    pids: [],
    gender: "female",
    born: "2008/3/1",
    locate: "淡路ファームパークイングランドの丘",
  },
  {
    id: 2,
    name: "ミリー",
    pids: [10,85],
    gender: "female",
    born: "2000/8/23-2017/1/30",
    locate: "多摩動物公園",
  },
  {
    id: 3,
    name: "ピックス",
    pids: [7],
    gender: "male",
    born: "2003/6/28-2019/1/21",
    locate: "平川動物公園",
  },
  {
    id: 4,
    name: "ティリー",
    pids: [106,24,86,90,15],
    gender: "female",
    born: "2009/12/15-2024/12/25",
    locate: "東山動植物園",
  },
  {
    id: 5,
    name: "ウメ",
    pids: [20,12,45],
    gender: "female",
    born: "2010/8/5-2022/11/21",
    locate: "王子動物園",
  },
  {
    id: 6,
    name: "だいち",
    pids: [],
    gender: "male",
    born: "2013/8/18",
    locate: "淡路ファームパークイングランドの丘",
  },
  {
    id: 7,
    name: "ミライ",
    pids: [3],
    gender: "female",
    born: "2008/10/25-2020/6/10",
    locate: "平川動物公園",
  },
  {
    id: 8,
    name: "ウミ",
    pids: [12,20],
    gender: "female",
    born: "2014/6/13",
    locate: "淡路ファームパークイングランドの丘",
  },
  {
    id: 9,
    name: "ホリー",
    pids: [15,24,106],
    gender: "female",
    born: "2013/12/25",
    locate: "東山動植物園",
  },
  {
    id: 10,
    name: "モモジ",
    pids: [2],
    gender: "male",
    born: "1997/2/7-2007/2/17",
    locate: "王子動物園",
  },
  {
    id: 11,
    name: "ハニー",
    pids: [],
    gender: "female",
    born: "2014/8/3-2024/8/15",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 12,
    name: "ウルル",
    pids: [8,5],
    gender: "male",
    born: "2007/5/26-2017/12/18",
    locate: "",
  },
  {
    id: 13,
    name: "ユメ",
    pids: [31,99,104],
    gender: "female",
    born: "2015/1/2-2025/3/23",
    locate: "平川動物公園",
  },
  {
    id: 14,
    name: "ジンベラン",
    pids: [105,16],
    gender: "female",
    born: "2013/2/23-2023/7/8",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 15,
    name: "タイチ",
    pids: [23,4,27,37,9],
    gender: "male",
    born: "2012/5/3-2022/9/29",
    locate: "平川動物公園",
  },
  {
    id: 16,
    name: "コロン",
    pids: [43,14,28,21,25],
    gender: "male",
    born: "2014/11/22",
    locate: "金沢動物園",
  },
  {
    id: 17,
    name: "チャーリー",
    pids: [35,26],
    gender: "male",
    born: "2014/11/27",
    locate: "多摩動物公園",
  },
  {
    id: 18,
    name: "モミジ",
    pids: [93],
    gender: "female",
    born: "2006/5/29-2015/8/21",
    locate: "王子動物園",
  },
  {
    id: 19,
    name: "リオ",
    pids: [],
    gender: "female",
    born: "2015/12/10",
    locate: "平川動物公園",
  },
  {
    id: 20,
    name: "ピーター",
    pids: [8,5,22],
    gender: "male",
    born: "2016/3/28",
    locate: "淡路ファームパークイングランドの丘",
  },
  {
    id: 21,
    name: "クイン",
    pids: [16],
    gender: "female",
    born: "2015/3/23-2023/5/31",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 22,
    name: "オウカ",
    pids: [39,20],
    gender: "female",
    born: "2016/9/25",
    locate: "王子動物園",
  },
  {
    id: 23,
    name: "りん",
    pids: [15,24],
    gender: "female",
    born: "2017/8/23",
    locate: "東山動植物園",
  },
  {
    id: 24,
    name: "イシン",
    pids: [27,23,4,9],
    gender: "male",
    born: "2017/5/14",
    locate: "東山動植物園",
  },
  {
    id: 25,
    name: "こまち",
    pids: [16],
    gender: "female",
    born: "2017/4/27",
    locate: "多摩動物公園",
  },
  {
    id: 26,
    name: "ぼたん",
    pids: [17],
    gender: "female",
    born: "2017/5/12-2024/12/13",
    locate: "金沢動物園",
  },
  {
    id: 27,
    name: "ななみ",
    pids: [15,24],
    gender: "female",
    born: "2018/7/7",
    locate: "東山動植物園",
  },
  {
    id: 28,
    name: "きらら",
    pids: [16],
    gender: "female",
    born: "2018/9/6",
    locate: "多摩動物公園",
  },
  {
    id: 29,
    name: "コタロウ (2015)",
    pids: [],
    gender: "male",
    born: "2015/9/25-2022/7/31",
    locate: "多摩動物公園",
  },
  {
    id: 30,
    name: "ヒマワリ",
    pids: [31,104],
    gender: "female",
    born: "2019/6/22",
    locate: "平川動物公園",
  },
  {
    id: 31,
    name: "アーチャー",
    pids: [46,48,13,38,47,30,37],
    gender: "male",
    born: "2019/4/26",
    locate: "平川動物公園",
  },
  {
    id: 32,
    name: "ハナ",
    pids: [],
    gender: "female",
    born: "2019/5/20",
    locate: "王子動物園",
  },
  {
    id: 33,
    name: "エマ",
    pids: [],
    gender: "female",
    born: "2018/12/6",
    locate: "王子動物園",
  },
  {
    id: 34,
    name: "ふく",
    pids: [42],
    gender: "female",
    born: "2019/6/12",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 35,
    name: "コハル",
    pids: [17],
    gender: "female",
    born: "2019/4/2",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 36,
    name: "つくし",
    pids: [49],
    gender: "female",
    born: "2020/9/3",
    locate: "平川動物公園",
  },
  {
    id: 37,
    name: "インディコ",
    pids: [15,31],
    gender: "female",
    born: "2019/12/22",
    locate: "平川動物公園",
  },
  {
    id: 38,
    name: "キボウ",
    pids: [31,104],
    gender: "female",
    born: "2019/10/17",
    locate: "平川動物公園",
  },
  {
    id: 39,
    name: "いぶき",
    pids: [22],
    gender: "male",
    born: "2020/8/27",
    locate: "王子動物園",
  },
  {
    id: 40,
    name: "イツキ",
    pids: [],
    gender: "male",
    born: "2020/4/3",
    locate: "王子動物園",
  },
  {
    id: 41,
    name: "ワトル",
    pids: [],
    gender: "female",
    born: "2020/5/14",
    locate: "東山動植物園",
  },
  {
    id: 42,
    name: "ソラ",
    pids: [51,34],
    gender: "male",
    born: "2020/6/14",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 43,
    name: "たんぽぽ",
    pids: [16],
    gender: "female",
    born: "2020/4/26",
    locate: "金沢動物園",
  },
  {
    id: 44,
    name: "シャイン",
    pids: [55],
    gender: "male",
    born: "2017/8/31-2022/1/6",
    locate: "王子動物園",
  },
  {
    id: 45,
    name: "アーティー",
    pids: [5],
    gender: "male",
    born: "2012/8/11-2017/7/27",
    locate: "金沢動物園",
  },
  {
    id: 46,
    name: "ヒナタ",
    pids: [31],
    gender: "female",
    born: "2021/3/27",
    locate: "平川動物公園",
  },
  {
    id: 47,
    name: "カナエ",
    pids: [31],
    gender: "female",
    born: "2021/6/13",
    locate: "平川動物公園",
  },
  {
    id: 48,
    name: "ピース",
    pids: [31],
    gender: "female",
    born: "2021/6/29",
    locate: "平川動物公園",
  },
  {
    id: 49,
    name: "ライト",
    pids: [36],
    gender: "male",
    born: "2021/5/14",
    locate: "平川動物公園",
  },
  {
    id: 50,
    name: "シャイニー",
    pids: [],
    gender: "female",
    born: "2021/5/13",
    locate: "王子動物園",
  },
  {
    id: 51,
    name: "ミラ",
    pids: [42],
    gender: "female",
    born: "2021/4/30",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 52,
    name: "あずま",
    pids: [],
    gender: "female",
    born: "2021/5/18",
    locate: "多摩動物公園",
  },
  {
    id: 53,
    name: "ニーナ",
    pids: [105],
    gender: "female",
    born: "2016/9/27-2020/5/4",
    locate: "多摩動物公園",
  },
  {
    id: 54,
    name: "ミナト",
    pids: [],
    gender: "male",
    born: "2014/6/12-2017/12/20",
    locate: "王子動物園",
  },
  {
    id: 55,
    name: "マイ",
    pids: [44],
    gender: "female",
    born: "2019/5/15-2022/6/21",
    locate: "王子動物園",
  },
  {
    id: 56,
    name: "タイヨウ",
    pids: [],
    gender: "male",
    born: "2022/8/11",
    locate: "平川動物公園",
  },
  {
    id: 57,
    name: "ししお",
    pids: [],
    gender: "male",
    born: "2022/4/4",
    locate: "平川動物公園",
  },
  {
    id: 58,
    name: "ノゾム",
    pids: [],
    gender: "male",
    born: "2022/2/26",
    locate: "淡路ファームパークイングランドの丘",
  },
  {
    id: 59,
    name: "おもち",
    pids: [],
    gender: "female",
    born: "2022/3/21",
    locate: "東山動植物園",
  },
  {
    id: 60,
    name: "スカイ",
    pids: [],
    gender: "male",
    born: "2022/4/20",
    locate: "東山動植物園",
  },
  {
    id: 61,
    name: "だいふく",
    pids: [],
    gender: "male",
    born: "2022/3/14",
    locate: "東山動植物園",
  },
  {
    id: 62,
    name: "ひなぎく",
    pids: [],
    gender: "female",
    born: "2021/12/15-2025/7/2",
    locate: "金沢動物園",
  },
  {
    id: 63,
    name: "ハリー",
    pids: [],
    gender: "male",
    born: "2022/4/22",
    locate: "金沢動物園",
  },
  {
    id: 64,
    name: "きんとき",
    pids: [],
    gender: "male",
    born: "2022/6/25",
    locate: "多摩動物公園",
  },
  {
    id: 65,
    name: "パピー",
    pids: [],
    gender: "female",
    born: "2011/6/23-2013/9/3",
    locate: "多摩動物公園",
  },
  {
    id: 66,
    name: "ニシチ",
    pids: [],
    gender: "male",
    born: "2019/2/7-2021/3/31",
    locate: "多摩動物公園",
  },
  {
    id: 67,
    name: "ツムギ",
    pids: [],
    gender: "female",
    born: "2023/5/13",
    locate: "平川動物公園",
  },
  {
    id: 68,
    name: "アラタ",
    pids: [],
    gender: "male",
    born: "2023/6/14",
    locate: "平川動物公園",
  },
  {
    id: 69,
    name: "ナギ",
    pids: [],
    gender: "female",
    born: "2023/7/31",
    locate: "淡路ファームパークイングランドの丘",
  },
  {
    id: 70,
    name: "アサヒ",
    pids: [],
    gender: "male",
    born: "2022/12/9",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 71,
    name: "スミレ",
    pids: [],
    gender: "female",
    born: "2024/9/11",
    locate: "平川動物公園",
  },
  {
    id: 72,
    name: "カスミ",
    pids: [],
    gender: "female",
    born: "2024/6/1",
    locate: "平川動物公園",
  },
  {
    id: 73,
    name: "スター",
    pids: [],
    gender: "male",
    born: "2023/11/18",
    locate: "平川動物公園",
  },
  {
    id: 74,
    name: "チャーボウ",
    pids: [],
    gender: "male",
    born: "2023/10/21",
    locate: "平川動物公園",
  },
  {
    id: 75,
    name: "オウキ",
    pids: [],
    gender: "male",
    born: "2024/6/12",
    locate: "王子動物園",
  },
  {
    id: 76,
    name: "もなか",
    pids: [],
    gender: "male",
    born: "2023/10/20",
    locate: "東山動植物園",
  },
  {
    id: 77,
    name: "さち",
    pids: [],
    gender: "female",
    born: "2024/5/9",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 78,
    name: "ポポロ",
    pids: [],
    gender: "male",
    born: "2024/4/22",
    locate: "金沢動物園",
  },
  {
    id: 79,
    name: "エイト",
    pids: [],
    gender: "male",
    born: "2024/11/24",
    locate: "平川動物公園",
  },
  {
    id: 80,
    name: "アース",
    pids: [],
    gender: "male",
    born: "2024/9/20",
    locate: "平川動物公園",
  },
  {
    id: 81,
    name: "ミラ仔",
    pids: [],
    gender: "male",
    born: "2024/6/23-2025/1/14",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 82,
    name: "",
    pids: [82,94],
    gender: "male",
    born: "",
    locate: "王子動物園",
  },
  {
    id: 83,
    name: "ピコ",
    pids: [84],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 84,
    name: "ジェックス",
    pids: [83],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 85,
    name: "ライタ",
    pids: [2],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 86,
    name: "アーチャー(東山)",
    pids: [4],
    gender: "male",
    born: "-2015/4/3",
    locate: "東山動植物園",
  },
  {
    id: 87,
    name: "カルゴア",
    pids: [0],
    gender: "female",
    born: "",
    locate: "東山動植物園",
  },
  {
    id: 88,
    name: "ボウ",
    pids: [98],
    gender: "male",
    born: "",
    locate: "",
  },
  {
    id: 89,
    name: "ジンベラン仔",
    pids: [],
    gender: "male",
    born: "-2023/7/9",
    locate: "埼玉こども動物自然公園",
  },
  {
    id: 90,
    name: "ピース♂",
    pids: [4,96],
    gender: "male",
    born: "",
    locate: "",
  },
  {
    id: 91,
    name: "ゆめ",
    pids: [92],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 92,
    name: "アーク",
    pids: [91],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 93,
    name: "パイン",
    pids: [18],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 94,
    name: "ティアラ",
    pids: [82],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 95,
    name: "ティムタム",
    pids: [96],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 96,
    name: "ライチ",
    pids: [95,90],
    gender: "female",
    born: "",
    locate: "",
  },
  {
    id: 97,
    name: "ジェイン",
    pids: [99,104],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 98,
    name: "ドリー",
    pids: [88,105],
    gender: "female",
    born: "",
    locate: "",
  },
  {
    id: 99,
    name: "バンブラ",
    pids: [13,103,97],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 100,
    name: "ココロ",
    pids: [102,104],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 101,
    name: "ブランディ",
    pids: [102],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 102,
    name: "フランク",
    pids: [101,100],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 103,
    name: "イト",
    pids: [99],
    gender: "female",
    born: "",
    locate: "",
  },
  {
    id: 104,
    name: "ブンダ",
    pids: [97,100,13,38,30],
    gender: "",
    born: "",
    locate: "",
  },
  {
    id: 105,
    name: "コタロウ",
    pids: [14,53,98],
    gender: "male",
    born: "",
    locate: "",
  },
  {
    id: 106,
    name: "マックス",
    pids: [4,9],
    gender: "male",
    born: "",
    locate: "",
  },
];

window.familyData = familyData;